[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://wcrkcuugancklxirqfyl.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_ccvNj5ojFxa0nZ4F0c8zgw_VIhwv34O"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
